version: 2
root-markers:
  - .git/
  - package.json

tools:
  black-action-format: &black-action-format
    format-command: "black --quiet --line-length=120 -"
    format-stdin: true

  isort: &isort
    format-command: "isort --stdout --profile black -"
    format-stdin: true

  stylua: &stylua
    format-command: "stylua -"
    format-stdin: true

  google-java-format: &google-java-format
    format-command: "google-java-format -"
    format-stdin: true

  prettierd: &prettierd
    format-command: "prettierd ${INPUT}"
    format-stdin: true

  mypy-lint: &mypy-lint
    prefix: mypy
    lint-command: "mypy --show-column-numbers --ignore-missing-imports"
    lint-formats:
      - "%f=%l:%c: %t%*[^:]: %m"
    root-markers:
      - setup.cfg
      - mypy.ini

  python-ruff: &python-ruff
    lint-command: "ruff check --line-length=120 --quiet ${INPUT}"
    lint-stdin: true
    lint-formats:
      - "%f=%l:%c: %trror: %m"
      - "%f=%l:%c: %tarning: %m"
      - "%f=%l:%c: %tote: %m"
      - "%f:%l:%c: %m"

  # FIXME
  djlint: &djlint
    lint-command: "djlint --check -"
    lint-stdin: true
    lint-formats:
      - "%f:%l:%c: %m"
    format-command: "djlint --reformat -"
    format-stdin: true

  php-lint: &php-lint
    lint-command: "php -l -d display_errors=STDERR -d log_errors=OFF"
    lint-stdin: true
    lint-ignore-exit-code: true
    lint-formats:
      - "%m in %.%# line %l"
    root-markers:
      - "composer.json"

  phpcs: &phpcs
    prefix: linter
    lint-command: "phpcs --no-colors --report=emacs -"
    lint-stdin: true
    lint-formats:
      - "%.%#:%l:%c: %trror - %m"
      - "%.%#:%l:%c: %tarning - %m"
    root-markers:
      - ".phpcs.xml"
      - "phpcs.xml"
      - ".phpcs.xml.dist"
      - "phpcs.xml.dist"
      - "composer.json"

  phpcbf: &phpcbf
    format-command: "phpcbf -"
    format-stdin: true

languages:
  python:
    - <<: *black-action-format
    - <<: *isort
    - <<: *mypy-lint
    - <<: *python-ruff
  java:
    - <<: *google-java-format
  javascript:
    - <<: *prettierd
  typescript:
    - <<: *prettierd
  javascriptreact:
    - <<: *prettierd
  typescriptreact:
    - <<: *prettierd
  yaml:
    - <<: *prettierd
  json:
    - <<: *prettierd
  jsonc:
    - <<: *prettierd
  html:
    - <<: *prettierd
  vue:
    - <<: *prettierd
  scss:
    - <<: *prettierd
  css:
    - <<: *prettierd
  less:
    - <<: *prettierd
  markdown:
    - <<: *prettierd
  markdown.mdx:
    - <<: *prettierd
  graphql:
    - <<: *prettierd
  handlebars:
    - <<: *prettierd
  lua:
    - <<: *stylua
  django:
    - <<: *djlint
  jinja.html:
    - <<: *djlint
  htmldjango:
    - <<: *djlint
  php:
    - <<: *phpcs
    - <<: *phpcbf
