#!/usr/bin/sh

docker run -e WATCHTOWER_CLEANUP="true" -d -v /var/run/docker.sock:/var/run/docker.sock --restart always containrrr/watchtower:latest

docker run -d --name searxng -p 8080:8080 -v ./searxng:/etc/searxng --restart always searxng/searxng:latest

docker run -d --gpus=all -v ollama:/root/.ollama -p 11434:11434 --name ollama ollama/ollama:latest

openai=$(gpg -d ~/openai.txt.asc)
docker run -e WEBUI_AUTH='False' \
  -e OPENAI_API_BASE_URLS="https://api.openai.com/v1" \
  -e OPENAI_API_KEYS="${openai}" \
  -d -p 3000:8080 --add-host=host.docker.internal:host-gateway \
  -v open-webui:/app/backend/data \
  --name open-webui \
  --restart always \
  ghcr.io/open-webui/open-webui:main

