#!/usr/bin/sh
# Install searxng separately as preferred method:
# https://docs.openwebui.com/tutorials/features/web_search/#searxng-docker

docker run --rm --name watchtower -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower:latest --run-once --include-restarting --include-stopped --cleanup

docker run -d --gpus=all -v ollama:/root/.ollama -p 11434:11434 --name ollama --restart always ollama/ollama:latest

openai=$(gpg -d ~/openai.txt.gpg)
docker run -e WEBUI_AUTH='False' \
  -e OPENAI_API_BASE_URLS="https://api.openai.com/v1" \
  -e OPENAI_API_KEYS="${openai}" \
  -d -p 3000:8080 --add-host=host.docker.internal:host-gateway \
  -v open-webui:/app/backend/data \
  --name open-webui \
  --restart always \
  ghcr.io/open-webui/open-webui:latest

